### ISSUE TITLE
Android 10 mattermost app title bar theme issue

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/canonical-mattermost-themes#2]
The title bar on Android 10 with dark canonical theme, needs to be deep aubergine color.

And when sidestage is opened, bright aubergine.

See screenshots.

Other native apps blend the color of the top bar.

**Comment by xnox** [comment]
![Screenshot_20200624-214543~2](https://user-images.githubusercontent.com/19779/85626137-78ecef80-b664-11ea-821c-792171f76207.png)
![Screenshot_20200624-214523~2](https://user-images.githubusercontent.com/19779/85626140-79858600-b664-11ea-9390-0afea1ecdbce.png)

**Comment by xnox** [comment]
The light gray should be bright aubergine.

The white bar, should be dark aubergine.

**Comment by anthonydillon** [comment]
@xnox Hi, I looked into this but could not replicate it. I do not see either bars on my phone using the app on Android 10. Am I missing something?

**Comment by xnox** [comment]
> @xnox Hi, I looked into this but could not replicate it. I do not see either bars on my phone using the app on Android 10. Am I missing something?

Let me walk over to your desk to show you waht i mean.... oh wait.....

It might be because i have dark theme on.
It might be because my phone has a notch (despite it not being in the way).
It might be because the aspect ratio of my phone is "long".

But yeah the gap, of odd color, between notification bar and "the app" is there.... and i got used to it.

I guess we can close this issue as incomplete until we have a better reproducer.

**Comment by anthonydillon** [comment]
Sorry, I imagine it's likely an issue with the application and the screen height as you mentioned but I will share this around the web team and see if anyone can replicate it.
