### ISSUE TITLE
Please use ubuntu font

### ISSUE THREAD

**Issue by xnox** [canonical-web-and-design/canonical-mattermost-themes#3]
It would be nice if the theme would somehow set to use the Ubuntu / Ubuntu Mono webfonts for mattermost.

**Comment by tbille** [comment]
@xnox that would great but this is not at a theme level at the moment. This is the list of stuff that we can tweak in the themes: https://docs.mattermost.com/help/settings/theme-colors.html

We should check if there is an issue about that on mattermost's repos.

**Comment by xnox** [comment]
Cool! Will report there.

**Comment by anthonydillon** [comment]
@xnox I'm sure you will find it but looks like that removed the ability to change the font in v5: https://github.com/mattermost/desktop/issues/958

**Comment by anthonydillon** [comment]
If there is anything you find or we can do please re-open.
