### ISSUE TITLE
Links in the dark theme are to dark

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/canonical-mattermost-themes#5]
Links are very hard to read on the dark theme:
![image](https://user-images.githubusercontent.com/1413534/85718544-86e35480-b6e6-11ea-8db2-8bac8e229183.png)

@lyubomir-popov @waynecrosby could you provide an alternative?

**Comment by waynecrosby** [comment]
@anthonydillon Is that #06c that we use for link colour in Vanilla?

**Comment by lyubomir-popov** [comment]
@anthonydillon This is what I use - our new link blue driven all the way to AAA contrast on #333 background (so I can see it while working outdoors on a sunny day :)

![image](https://user-images.githubusercontent.com/2741678/85731061-180bf880-b6f2-11ea-86dc-27b42619ca6a.png)

My whole theme:

![image](https://user-images.githubusercontent.com/2741678/85734215-c31db180-b6f4-11ea-8dfe-62b357d7d04a.png)


```
{"sidebarBg":"#2C001E",
"sidebarText":"#ffffff",
"sidebarUnreadText":"#ffffff",
"sidebarTextHoverBg":"#431A35",
"sidebarTextActiveBorder":"#5E2750",
"sidebarTextActiveColor":"#ffffff",
"sidebarHeaderBg":"#2C001E",
"sidebarHeaderTextColor":"#ffffff",
"onlineIndicator":"#0e8420",
"awayIndicator":"#f99b11",
"dndIndicator":"#c7162b",
"mentionBg":"#333",
"mentionBj":"#222",
"mentionColor":"#fff",
"centerChannelBg":"#1f1f1f",
"centerChannelColor":"#ffffff",
"newMessageSeparator":"#333",
"linkColor":"#8FC7FF",
"buttonBg":"#0e8420",
"buttonColor":"#ffffff",
"errorTextColor":"#c7162b",
"mentionHighlightBg":"#06C",
"mentionHighlightLink":"#fff",
"codeTheme":"github"
}
```

**Comment by lyubomir-popov** [comment]
BTW I intend to submit a working group proposal with this as the default link for the vanilla dark theme, which will enable us to use links in the dark vanilla tooltips safely.
