### ISSUE TITLE
 The Canonical Dark theme doesn't have syntax highlighting

### ISSUE THREAD

**Issue by d0ugal** [canonical-web-and-design/canonical-mattermost-themes#9]
For some reason the Canonical Dark theme doesn't colour code. The Canonical Light and all other themes do.

`"codeTheme": "github-dark"`

Maybe this should be "monokai" or another name? I guess github-dark doesn't exist?

**Comment by d0ugal** [comment]
Moved from https://bugs.launchpad.net/canonical-mattermost/+bug/1887958

**Comment by anthonydillon** [comment]
The codeTheme does exist but there seems to being some issues with updating themes automatically. Could you switch to another theme and back to the Canonical dark theme and see if that refreshes the styles. Another option to test this is to copy these settings as a custom theme and see it work. If you still see the issue please reopen and comment.

**Comment by d0ugal** [comment]
Changing themes works very reliably for me with every theme. The only difference is that Canonical Dark does not highlight the code. If I edit the theme and change it to `"github"` or `"monokai"` then it also works fine. If I use `"github-dark"` on another theme it then also drops the colours.

FWIW, I tested it with a very simple message in a chat with myself.

    ```python
    print(1)
    print("two")
    ```

I am also using the MM snap if that makes a difference.

**Comment by anthonydillon** [comment]
Oh I see what you mean the syntax highlighting is missing. Strange, the classes are there.

**Comment by anthonydillon** [comment]
@d0ugal PR ready if you wanted to review ^

**Comment by d0ugal** [comment]
Looks good to me, thanks!

**Comment by Saviq** [comment]
Hey @anthonydillon, we're still seeing the issue and @hatched has found something.

**Comment by hatched** [comment]
I dug a bit deeper. It looks like the culprit is the `monokai` theme not having the appropriate classes (or maybe isn't being applied at all). Maybe we can change that to something else? Does this need to be installed separately?

https://github.com/canonical-web-and-design/canonical-mattermost-themes/blob/master/darkTheme.json#L25

**Comment by anthonydillon** [comment]
It was fixed in the latest released version: https://github.com/canonical-web-and-design/canonical-mattermost-themes/releases/tag/v1.0.2

Here is the ticket to release it: https://portal.admin.canonical.com/C126959/

**Comment by relaxdiego** [comment]
> It was fixed in the latest released version: https://github.com/canonical-web-and-design/canonical-mattermost-themes/releases/tag/v1.0.2
> 
> Here is the ticket to release it: https://portal.admin.canonical.com/C126959/

Just confirming that I pasted the contents of the canonical dark theme in my MM client (MacOS) custom theme textbox and it fixed the syntax highlighting issue.

**Comment by relaxdiego** [comment]
Although, I checked with the mobile client (iPhone) and the syntax highlighting isn't working.

**Comment by anthonydillon** [comment]
We are unfortunately blocked waiting for this change to be rolled out.

**Comment by anthonydillon** [comment]
This has now been released. Please change your theme to the light one and then back to the dark one to get the latest changes.

![image](https://user-images.githubusercontent.com/1413534/93301669-b50d9780-f7f0-11ea-853d-d949107f99ea.png)
